# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "77aea4b5141f35938a18a48b1f314e46"
name = "Bundlify: AI Bundles"
application_url = "https://bundlify-ai-bundles-69a6.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://bundlify-ai-bundles-69a6.vercel.app/api/auth" ]

[build]
automatically_update_urls_on_dev = true

# Public Repository Auto-Deploy Test
